version: "3"

networks:
  kijiji-network:
    driver: "bridge"

services:
  app:
    build:
      context: .
    ports:
      - "4001:4000"
    volumes: 
      - "${PWD}:/usr/src/app"
    networks:
      - kijiji-network
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - kijiji-network